--CS4
CREATE OR REPLACE VIEW PROJECT_UV_TRUONGDONVI_PHANCONG
AS 
    SELECT* FROM PROJECT_PHANCONG PC
    WHERE EXISTS (SELECT HP.MAHP 
    FROM PROJECT_HOCPHAN HP JOIN PROJECT_DONVI DV ON HP.MADV = DV.MADV
    WHERE HP.MAHP = PC.MAHP AND DV.TRGDV = SYS_CONTEXT('USEREVN','SESSION_USER'));
/
CREATE OR REPLACE VIEW PROJECT_SV_TRUONGDONVI_PHANCONG
AS
    SELECT* FROM PROJECT_PHANCONG PC
    WHERE EXISTS(SELECT NS.MANV FROM PROJECT_NHANSU NS
    JOIN PROJECT_DONVI DV ON NS.MADV = DV.MADV 
    WHERE NS.MANV = PC.MAGV AND DV.TRGDV = SYS_CONTEXT('USEREVN','SESSION_USER'));
/
CREATE OR REPLACE PROCEDURE PROJECT_CS#4
AS
    BEGIN
        EXECUTE IMMEDIATE 'ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE';
        EXECUTE IMMEDIATE 'GRANT C##P_GIANGVIEN TO C##P_TRUONGDONVI';
        EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, DELETE, UPDATE ON PROJECT_UV_TRUONGDONVI_PHANCONG TO C##P_TRUONGDONVI';
        EXECUTE IMMEDIATE 'GRANT SELECT ON PROJECT_SV_TRUONGDONVI_PHANCONG TO C##P_TRUONGDONVI';
    END;
/
--CS5
CREATE OR REPLACE VIEW PROJECT_UV_TRUONGKHOA_PHANCONG
AS
    SELECT* FROM PROJECT_PHANCONG PC
    WHERE EXISTS (SELECT HP.MAHP 
    FROM PROJECT_HOCPHAN HP JOIN PROJECT_DONVI DV ON HP.MADV = DV.MADV
    WHERE HP.MAHP = PC.MAHP AND DV.TENDV = N'Văn phòng khoa');
CREATE OR REPLACE PROCEDURE PROJECT_CS#5
AS
    BEGIN
        EXECUTE IMMEDIATE 'ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE';
        EXECUTE IMMEDIATE 'GRANT C##P_GIANGVIEN TO C##P_TRUONGKHOA';
        EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE ON PROJECT_UV_TRUONGKHOA_PHANCONG TO C##P_TRUONGKHOA';
        EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,DELETE,UPDATE ON PROJECT_NHANSU TO C##P_TRUONGKHOA';
        EXECUTE IMMEDIATE 'GRANT SELECT ON PROJECT_DANGKY TO C##P_TRUONGKHOA';
        EXECUTE IMMEDIATE 'GRANT SELECT ON PROJECT_DONVI TO C##P_TRUONGKHOA';
        EXECUTE IMMEDIATE 'GRANT SELECT ON PROJECT_HOCPHAN TO C##P_TRUONGKHOA';
        EXECUTE IMMEDIATE 'GRANT SELECT ON PROJECT_KHMO TO C##P_TRUONGKHOA';
        EXECUTE IMMEDIATE 'GRANT SELECT ON PROJECT_PHANCONG TO C##P_TRUONGKHOA';
        EXECUTE IMMEDIATE 'GRANT SELECT ON PROJECT_SINHVIEN TO C##P_TRUONGKHOA';
    END;
/