ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE
BEGIN
    DBMS_RLS.DROP_POLICY(
        OBJECT_SCHEMA =>'C##ADMIN',
        OBJECT_NAME=>'project_sinhvien',
        POLICY_NAME =>'PC1_1'
    );
END;
/

BEGIN
    DBMS_RLS.DROP_POLICY(
        OBJECT_SCHEMA =>'C##ADMIN',
        OBJECT_NAME=>'PROJECT_DANGKY',
        POLICY_NAME =>'PC3'
    );
END;
/
BEGIN
 DBMS_RLS.DROP_POLICY(
 OBJECT_SCHEMA =>'C##ADMIN',
 OBJECT_NAME=>'project_KHMO',
 POLICY_NAME =>'PC2');
END; 
/
BEGIN
 DBMS_RLS.DROP_POLICY(
 OBJECT_SCHEMA =>'C##ADMIN',
 OBJECT_NAME=>'project_HOCPHAN',
    POLICY_NAME =>'PC3');
END; 
/
BEGIN
    DBMS_RLS.DROP_POLICY(
        OBJECT_SCHEMA =>'C##ADMIN',
        OBJECT_NAME=>'project_KHMO',
        POLICY_NAME =>'PC4'
    );
END;
/
BEGIN
    DBMS_RLS.DROP_POLICY(
        OBJECT_SCHEMA =>'C##ADMIN',
        OBJECT_NAME=>'project_DANGKY',
        POLICY_NAME =>'PC5'
    );
END;
/
BEGIN
    DBMS_RLS.DROP_POLICY(
        OBJECT_SCHEMA =>'C##ADMIN',
        OBJECT_NAME=>'project_DANGKY',
        POLICY_NAME =>'PC6'
    );
END;
-- Trên quan hệ SINHVIEN, sinh viên chỉ được xem thông tin của chính mình
CREATE OR REPLACE FUNCTION PC1_FUNCTION (
    P_SCHEMA VARCHAR2,
    P_OBJ VARCHAR2
    
)
RETURN VARCHAR2
AS
    USER VARCHAR2(100); -- Corrected the data type declaration
BEGIN
    USER := SYS_CONTEXT('USERENV','SESSION_USER'); -- Corrected the typo in USERENV
    RETURN 'MASV = ''' || USER || '''';
END;
/
BEGIN
 DBMS_RLS.ADD_POLICY(
 OBJECT_SCHEMA =>'C##ADMIN',
 OBJECT_NAME=>'project_sinhvien',
 POLICY_NAME =>'PC1',
 POLICY_FUNCTION=>'PC1_FUNCTION',
 STATEMENT_TYPES=>'SELECT');
END; 
/
BEGIN
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA =>'C##ADMIN',
        OBJECT_NAME=>'PROJECT_DANGKY',
        POLICY_NAME =>'PC5',
        POLICY_FUNCTION=>'PC1_FUNCTION',
        STATEMENT_TYPES=>'INSERT, DELETE',
        UPDATE_CHECK => TRUE
    );
END;
/
BEGIN
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA =>'C##ADMIN',
        OBJECT_NAME=>'PROJECT_DANGKY',
        POLICY_NAME =>'PC6',
        POLICY_FUNCTION=>'PC1_FUNCTION',
        STATEMENT_TYPES=>'SELECT'
    );
END;
-- Chỉnh sửa thông tin địa chỉ (ĐCHI) và số điện thoại liên lạc (ĐT) của chính sinh viên.
CREATE OR REPLACE FUNCTION PC1_FUNCTION (
    P_SCHEMA VARCHAR2,
    P_OBJ VARCHAR2
)
RETURN VARCHAR2
AS
    USER VARCHAR2(100); -- Corrected the data type declaration
BEGIN
    USER := SYS_CONTEXT('USERENV','SESSION_USER'); -- Corrected the typo in USERENV
    RETURN 'MASV = ''' || USER || '''';
END;
/
BEGIN
 DBMS_RLS.ADD_POLICY(
 OBJECT_SCHEMA =>'C##ADMIN',
 OBJECT_NAME=>'project_sinhvien',
 POLICY_NAME =>'PC1_1',
 POLICY_FUNCTION=>'PC1_FUNCTION',
 STATEMENT_TYPES=>'UPDATE' );
END; 

--- Xem danh sách tất cả học phần (HOCPHAN), kế hoạch mở môn (KHMO) của chương trình đào tạo mà sinh viên đang theo học.
/
CREATE OR REPLACE FUNCTION PC2_FUNCTION
 (P_SCHEMA VARCHAR2, P_OBJ VARCHAR2)
RETURN VARCHAR2
AS
 MA VARCHAR2(5);
 STRSQL VARCHAR2(2000);
 CURSOR CUR IS (SELECT MAHP
 FROM PROJECT_DANGKY
 WHERE MASV = SYS_CONTEXT('USERENV','SESSION_USER')
);
BEGIN
 OPEN CUR;
 LOOP
 FETCH CUR INTO MA;
 EXIT WHEN CUR%NOTFOUND;
 IF (STRSQL IS NOT NULL) THEN
 STRSQL := STRSQL ||''',''';
 END IF;
 STRSQL := STRSQL || MA;
 END LOOP;
 RETURN 'MAHP IN ('''||STRSQL||''')';
END; 
BEGIN
 DBMS_RLS.ADD_POLICY(
 OBJECT_SCHEMA =>'C##ADMIN',
 OBJECT_NAME=>'project_KHMO',
 POLICY_NAME =>'PC2',
 POLICY_FUNCTION=>'PC2_FUNCTION',
 STATEMENT_TYPES=>'SELECT'
 );
END; 
/
CREATE OR REPLACE FUNCTION PC3_FUNCTION
  (P_SCHEMA VARCHAR2, P_OBJ VARCHAR2)
RETURN VARCHAR2
AS
  MA VARCHAR2(10);
  STRSQL VARCHAR2(2000);
  CURSOR CUR IS (
    SELECT MAHP
    FROM PROJECT_DANGKY
    WHERE MASV = SYS_CONTEXT('USERENV','SESSION_USER'));
BEGIN
  OPEN CUR;
  LOOP
    FETCH CUR INTO MA;
    EXIT WHEN CUR%NOTFOUND;
    IF (STRSQL IS NOT NULL) THEN
      STRSQL := STRSQL ||','''; -- Corrected concatenation operator
    END IF;
    STRSQL := STRSQL || MA;
  END LOOP;
  RETURN 'MAHP IN ('''||STRSQL||''')';
END;
/

BEGIN
  DBMS_RLS.ADD_POLICY(
    OBJECT_SCHEMA =>'C##ADMIN',
    OBJECT_NAME=>'project_HOCPHAN',
    POLICY_NAME =>'PC3',
    POLICY_FUNCTION=>'PC3_FUNCTION',
    STATEMENT_TYPES=>'SELECT',
    UPDATE_CHECK => TRUE
  );
END;
/
CREATE OR REPLACE FUNCTION PC4_FUNCTION
  (P_SCHEMA VARCHAR2, P_OBJ VARCHAR2)
RETURN VARCHAR2
AS
  MA VARCHAR(5);
  STRSQL VARCHAR2(2000);
  CURSOR CUR IS 
    SELECT MACT
    FROM PROJECT_SINHVIEN
    WHERE MASV = SYS_CONTEXT('USERENV','SESSION_USER');
BEGIN
  STRSQL := ''; 
  OPEN CUR;
  LOOP
    FETCH CUR INTO MA;
    EXIT WHEN CUR%NOTFOUND;
    IF (STRSQL IS NOT NULL) THEN
      STRSQL := STRSQL || ',''' || MA || ''''; -- Corrected concatenation operator
    ELSE
      STRSQL := '''' || MA || ''''; -- Corrected concatenation operator
    END IF;
  END LOOP;
  RETURN 'MACT IN (' || STRSQL || ')';
END;
/
BEGIN
  DBMS_RLS.ADD_POLICY(
    OBJECT_SCHEMA =>'C##ADMIN',
    OBJECT_NAME=>'PROJECT_KHMO', -- Corrected table name to uppercase
    POLICY_NAME =>'PC4',
    POLICY_FUNCTION=>'PC4_FUNCTION',
    STATEMENT_TYPES=>'SELECT',
    UPDATE_CHECK => TRUE
  );
END;
/

--- Thêm, Xóa các dòng dữ liệu đăng ký học phần (ĐANGKY) liên quan đến chính sinh viên đó trong học kỳ của năm học hiện tại (nếu thời điểm hiệu chỉnh đăng ký còn hợp lệ).
--- Sinh viên được Xem tất cả thông tin trên quan hệ ĐANGKY tại các dòng dữ liệu liên quan đến chính sinh viên


BEGIN
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA =>'C##ADMIN',
        OBJECT_NAME=>'PROJECT_DANGKY',
        POLICY_NAME =>'PC6',
        POLICY_FUNCTION=>'PC1_FUNCTION',
        STATEMENT_TYPES=>'SELECT'
    );
END;
/
REVOKE UPDATE ON PROJECT_SINHVIEN FROM C##P_SINHVIEN;
grant SELECT ON PROJECT_SINHVIEN TO C##P_SINHVIEN;
grant UPDATE (DCHI,DT) ON PROJECT_SINHVIEN TO C##P_SINHVIEN;

GRANT SELECT,UPDATE ON PROJECT_DANGKY TO C##P_SINHVIEN;
GRANT SELECT ON PROJECT_HOCPHAN TO C##P_SINHVIEN;
GRANT SELECT ON PROJECT_KHMO TO C##P_SINHVIEN;

GRANT EXECUTE ON PC1_FUNCTION TO C##P_SINHVIEN;
GRANT EXECUTE ON PC2_FUNCTION TO C##P_SINHVIEN;
GRANT EXECUTE ON PC3_FUNCTION TO C##P_SINHVIEN;
GRANT EXECUTE ON PC4_FUNCTION TO C##P_SINHVIEN;
GRANT EXECUTE ON PC5_FUNCTION TO C##P_SINHVIEN;
GRANT EXECUTE ON PC6_FUNCTION TO C##P_SINHVIEN;
GRANT C##P_SINHVIEN TO SV1;
