--SELECT VALUE FROM v$option WHERE parameter = 'Oracle Label Security';
BEGIN
    SA_POLICY_ADMIN.REMOVE_TABLE_POLICY('AGENCY_POLICY','ADMIN_OLS','PROJECT_OLS_THONGBAO');
END;
/
BEGIN
  SA_SYSDBA.DROP_POLICY(
    policy_name => 'agency_policy'
  );
END;
/

DROP TABLE PROJECT_OLS_THONGBAO;

BEGIN
 SA_SYSDBA.CREATE_POLICY(
 policy_name => 'agency_policy',
 column_name => 'agency_label'
);
END;
/
EXEC SA_SYSDBA.ENABLE_POLICY ('agency_policy'); 

EXECUTE SA_COMPONENTS.CREATE_LEVEL('agency_policy',20,'SV','C##P_SINHVIEN');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('agency_policy',40,'NV','C##P_NVCOBAN');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('agency_policy',60,'GVU','C##P_GIAOVU'); 
EXECUTE SA_COMPONENTS.CREATE_LEVEL('agency_policy',80,'GV','C##P_GIANGVIEN');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('agency_policy',100,'TDV','C##P_TRUONGDONVI');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('agency_policy',120,'TK','C##P_TRUONGKHOA');

--->TẠO COMPARTMENT
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('agency_policy',20,'HTTT','Information System');
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('agency_policy',40,'CNPM','Software Engineering'); 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('agency_policy',60,'KHMT','Computer Science');
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('agency_policy',80,'CNTT','Knowledge Technology'); 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('agency_policy',100,'TGMT','Computer Vision');
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('agency_policy',120,'MMT','Computer Network'); 

--->TẠO GROUP
EXECUTE SA_COMPONENTS.CREATE_GROUP('agency_policy',50,'CS1','AGENCY1');
EXECUTE SA_COMPONENTS.CREATE_GROUP('agency_policy',100,'CS2','AGENCY2');
/

CREATE TABLE PROJECT_OLS_THONGBAO
(
    ID NUMBER(10), 
    CONTENT NVARCHAR2(1000), 
    
    PRIMARY KEY(ID)
);

INSERT INTO PROJECT_OLS_THONGBAO VALUES(1, 'THONG BAO NAY DANH CHO TDV');
INSERT INTO PROJECT_OLS_THONGBAO VALUES(2, 'THONG BAO NAY DANH CHO SINH VIEN NGANH HTTT CS1');
INSERT INTO PROJECT_OLS_THONGBAO VALUES(3, 'THONG BAO NAY DANH CHO TRUONG BO MON KHMT CUA CO SO 1');
INSERT INTO PROJECT_OLS_THONGBAO VALUES(4, 'THONG BAO NAY DANH CHO TRUONG BO MON KHMT CUA 2 CO SO');
INSERT INTO PROJECT_OLS_THONGBAO VALUES(5, 'THONG BAO NAY DANH CHO TOAN BO GIANG VIEN CO SO 2');
INSERT INTO PROJECT_OLS_THONGBAO VALUES(6, 'THONG BAO NAY DANH CHO GIAO VU');
INSERT INTO PROJECT_OLS_THONGBAO VALUES(7, 'THONG BAO NAY DANH CHO TRUONG BO MON CNPM CO SO 1 VA CO SO 2');


--B7: CẬP NHẬT NHÃN TRONG BẢNG
BEGIN

 SA_POLICY_ADMIN.APPLY_TABLE_POLICY (
 POLICY_NAME => 'AGENCY_POLICY',
 SCHEMA_NAME => 'ADMIN_OLS',
 TABLE_NAME => 'PROJECT_OLS_THONGBAO',
 TABLE_OPTIONS => 'NO_CONTROL'
 );
END; 
/
SELECT * FROM ADMIN_OLS.PROJECT_OLS_THONGBAO;

BEGIN
    SA_LABEL_ADMIN.CREATE_LABEL (
        policy_name  => 'AGENCY_POLICY',
        label_tag    => 1100,
        label_value  => 'TDV', -- SENSITIVE level for the HR compartment
        data_label   => TRUE);
    
    SA_LABEL_ADMIN.CREATE_LABEL (
        policy_name  => 'AGENCY_POLICY',
        label_tag    => 1200,
        label_value  => 'SV:HTTT:CS1', -- HIGHLY_SENSITIVE level for the HR compartment
        data_label   => TRUE);
    SA_LABEL_ADMIN.CREATE_LABEL (
        policy_name  => 'AGENCY_POLICY',
        label_tag    => 1300,
        label_value  => 'TDV:KHMT:CS1', -- HIGHLY_SENSITIVE level for the HR compartment
        data_label   => TRUE);
    SA_LABEL_ADMIN.CREATE_LABEL (
        policy_name  => 'AGENCY_POLICY',
        label_tag    => 1400,
        label_value  => 'TDV:KHMT:CS1,CS2', -- HIGHLY_SENSITIVE level for the HR compartment
        data_label   => TRUE);
    SA_LABEL_ADMIN.CREATE_LABEL (
        policy_name  => 'AGENCY_POLICY',
        label_tag    => 1500,
        label_value  => 'GV::CS2', -- HIGHLY_SENSITIVE level for the HR compartment
        data_label   => TRUE);
    SA_LABEL_ADMIN.CREATE_LABEL (
        policy_name  => 'AGENCY_POLICY',
        label_tag    => 1600,
        label_value  => 'GVU', -- HIGHLY_SENSITIVE level for the HR compartment
        data_label   => TRUE);
    SA_LABEL_ADMIN.CREATE_LABEL (
        policy_name  => 'AGENCY_POLICY',
        label_tag    => 1700,
        label_value  => 'TDV:CNPM:CS1,CS2', -- HIGHLY_SENSITIVE level for the HR compartment
        data_label   => TRUE);
END;
/


UPDATE ADMIN_OLS.PROJECT_OLS_THONGBAO
SET AGENCY_LABEL = CHAR_TO_LABEL('AGENCY_POLICY','TDV')
WHERE ID = 1;
UPDATE ADMIN_OLS.PROJECT_OLS_THONGBAO
SET AGENCY_LABEL = CHAR_TO_LABEL('AGENCY_POLICY','SV:HTTT:CS1')
WHERE ID = 2;
UPDATE ADMIN_OLS.PROJECT_OLS_THONGBAO
SET AGENCY_LABEL = CHAR_TO_LABEL('AGENCY_POLICY','TDV:KHMT:CS1')
WHERE ID = 3;
UPDATE ADMIN_OLS.PROJECT_OLS_THONGBAO
SET AGENCY_LABEL = CHAR_TO_LABEL('AGENCY_POLICY','TDV:KHMT:CS1,CS2')
WHERE ID = 4;
UPDATE ADMIN_OLS.PROJECT_OLS_THONGBAO
SET AGENCY_LABEL = CHAR_TO_LABEL('AGENCY_POLICY','GV::CS2')
WHERE ID = 5;
UPDATE ADMIN_OLS.PROJECT_OLS_THONGBAO
SET AGENCY_LABEL = CHAR_TO_LABEL('AGENCY_POLICY','GVU')
WHERE ID = 6;
UPDATE ADMIN_OLS.PROJECT_OLS_THONGBAO
SET AGENCY_LABEL = CHAR_TO_LABEL('AGENCY_POLICY','TDV:CNPM:CS1,CS2')
WHERE ID = 7;
--
--UPDATE PROJECT_OLS_THONGBAO
--SET AGENCY_LABEL = CHAR_TO_LABEL('AGENCY_POLICY','SV');



BEGIN
SA_POLICY_ADMIN.REMOVE_TABLE_POLICY('AGENCY_POLICY','ADMIN_OLS','PROJECT_OLS_THONGBAO');

SA_POLICY_ADMIN.APPLY_TABLE_POLICY (
 policy_name => 'AGENCY_POLICY',
 schema_name => 'ADMIN_OLS',
 table_name => 'PROJECT_OLS_THONGBAO',
 table_options => 'LABEL_DEFAULT,READ_CONTROL',
predicate => NULL
);
END; 
/
--ALTER SESSION SET CONTAINER= PROJECT_DBMANAGEMENT; SHOW CON_NAME; 

drop user GIAOVU cascade;
drop user TRUONGKHOA cascade;
CREATE USER GIAOVU IDENTIFIED BY 123;
GRANT CONNECT TO GIAOVU;
GRANT SELECT ON ADMIN_OLS.PROJECT_OLS_THONGBAO TO GIAOVU;


CREATE USER TRUONGKHOA IDENTIFIED BY 123;
GRANT CONNECT TO TRUONGKHOA;
GRANT SELECT ON ADMIN_OLS.PROJECT_OLS_THONGBAO TO TRUONGKHOA;

CREATE USER TRUONGBOMON IDENTIFIED BY 123;
GRANT CONNECT TO TRUONGBOMON;
GRANT SELECT ON ADMIN_OLS.PROJECT_OLS_THONGBAO TO TRUONGBOMON;

CREATE USER GIANGVIEN IDENTIFIED BY 123;
GRANT CONNECT TO GIANGVIEN;
GRANT SELECT ON ADMIN_OLS.PROJECT_OLS_THONGBAO TO GIANGVIEN;

BEGIN
    SA_USER_ADMIN.SET_USER_LABELS('AGENCY_POLICY','GIAOVU','GVU');
    SA_USER_ADMIN.SET_USER_LABELS('AGENCY_POLICY','GIANGVIEN','GV:CNPM:CS2');
    SA_USER_ADMIN.SET_USER_LABELS('AGENCY_POLICY','TRUONGBOMON','TDV:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS2');
    SA_USER_ADMIN.SET_USER_LABELS('AGENCY_POLICY','TRUONGKHOA','TK:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS1,CS2');

END;
COMMIT;



SELECT * FROM DBA_SA_LEVELS; 
SELECT * FROM DBA_SA_COMPARTMENTS;
SELECT * FROM DBA_SA_GROUPS;
select* from all_sa_labels;
SELECT*FROM ADMIN_OLS.PROJECT_OLS_THONGBAO
--============================================================================================================
