--CS3
CREATE OR REPLACE VIEW GIAOVU_PHANCONG AS
SELECT * FROM PROJECT_PHANCONG
WHERE MAHP IN (SELECT MAHP FROM PROJECT_HOCPHAN WHERE MADV = (SELECT MADV FROM PROJECT_DONVI WHERE TENDV = 'Văn phòng khoa'));

CREATE OR REPLACE VIEW GIAOVU_DANGKY AS
SELECT * FROM PROJECT_DANGKY
WHERE TRUNC(SYSDATE) BETWEEN (SELECT TRUNC(ADD_MONTHS(TO_DATE('01-01-' || NAM, 'DD-MM-YYYY'), (HK - 1) * 4)) FROM PROJECT_KHMO WHERE MAHP = PROJECT_DANGKY.MAHP AND HK = PROJECT_DANGKY.HK AND NAM = PROJECT_DANGKY.NAM)
AND (SELECT TRUNC(ADD_MONTHS(TO_DATE('01-01-' || NAM, 'DD-MM-YYYY'), (HK - 1) * 4) + 14) FROM PROJECT_KHMO WHERE MAHP = PROJECT_DANGKY.MAHP AND HK = PROJECT_DANGKY.HK AND NAM = PROJECT_DANGKY.NAM);

CREATE OR REPLACE PROCEDURE GRANT_ROLE_GIAOVU AS
BEGIN
    -- Grant C##P_NVCOBAN role to C##P_GIAOVU
    EXECUTE IMMEDIATE 'GRANT C##P_NVCOBAN TO C##P_GIAOVU';

    -- Grant select, insert, update on SINHVIEN, DONVI, HOCPHAN, KHMO to C##P_GIAOVU
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE ON PROJECT_SINHVIEN TO C##P_GIAOVU';
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE ON PROJECT_DONVI TO C##P_GIAOVU';
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE ON PROJECT_HOCPHAN TO C##P_GIAOVU';
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE ON PROJECT_KHMO TO C##P_GIAOVU';

    -- Grant select on PHANCONG to C##P_GIAOVU
    EXECUTE IMMEDIATE 'GRANT SELECT ON PROJECT_PHANCONG TO C##P_GIAOVU';

    -- Grant delete, insert on DANGKY to C##P_GIAOVU
    EXECUTE IMMEDIATE 'GRANT DELETE, INSERT ON PROJECT_DANGKY TO C##P_GIAOVU';
END;
/


