------------------------------------------CS1------------------------------------------------
CREATE OR REPLACE VIEW PROJECT_NVCOBAN_XEMTHONGTINCANHAN
AS SELECT *
FROM PROJECT_NHANSU
WHERE USERNAME = SYS_CONTEXT('USERENV', 'SESSION_USER');

CREATE OR REPLACE VIEW PROJECT_NVCOBAN_UPDATESDT
AS SELECT DT
FROM PROJECT_NHANSU
WHERE USERNAME = SYS_CONTEXT('USERENV', 'SESSION_USER');

CREATE OR REPLACE PROCEDURE PROJECT_CAIDAT_CS1 AS
    STRSQL VARCHAR2(2000);
BEGIN
    STRSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE';
    EXECUTE IMMEDIATE STRSQL;
    STRSQL := 'GRANT SELECT ON PROJECT_NVCOBAN_XEMTHONGTINCANHAN TO C##P_NVCOBAN';
    EXECUTE IMMEDIATE STRSQL;
    STRSQL := 'GRANT UPDATE ON PROJECT_NVCOBAN_UPDATESDT TO C##P_NVCOBAN';
    EXECUTE IMMEDIATE STRSQL;
    
    STRSQL := 'GRANT SELECT ON PROJECT_SINHVIEN TO C##P_NVCOBAN';
    EXECUTE IMMEDIATE STRSQL;
    STRSQL := 'GRANT SELECT ON PROJECT_DONVI TO C##P_NVCOBAN';
    EXECUTE IMMEDIATE STRSQL;
    STRSQL := 'GRANT SELECT ON PROJECT_HOCPHAN TO C##P_NVCOBAN';
    EXECUTE IMMEDIATE STRSQL;
    STRSQL := 'GRANT SELECT ON PROJECT_KHMO TO C##P_NVCOBAN';
    EXECUTE IMMEDIATE STRSQL;
    
    STRSQL := 'GRANT CONNECT, CREATE SESSION TO C##P_NVCOBAN';
    EXECUTE IMMEDIATE STRSQL;
    

    
END;
/

----------------------------------------------CS2------------------------------------------------
CREATE OR REPLACE VIEW PROJECT_GIANGVIEN_XEMPHANCONGCANHAN
AS SELECT PC.MAGV, PC.MAHP, PC.HK, PC.NAM, PC.MACT
FROM PROJECT_NHANSU NS JOIN PROJECT_PHANCONG PC ON NS.MANV = PC.MAGV
WHERE USERNAME = SYS_CONTEXT('USERENV', 'SESSION_USER');

CREATE OR REPLACE VIEW PROJECT_GIANGVIEN_XEMDANGKYDCPHANCONG
AS SELECT DK.*
FROM PROJECT_NHANSU NS JOIN PROJECT_DANGKY DK ON DK.MAGV = NS.MANV
WHERE USERNAME = SYS_CONTEXT('USERENV', 'SESSION_USER'); 

CREATE OR REPLACE VIEW PROJECT_GIANGVIEN_CAPNHATDIEMSO
AS SELECT DK.MASV,DK.DIEMTHI, DK.DIEMQT, DK.DIEMCK, DK.DIEMTK
FROM PROJECT_NHANSU NS JOIN PROJECT_DANGKY DK ON DK.MAGV = NS.MANV
WHERE USERNAME = SYS_CONTEXT('USERENV', 'SESSION_USER'); 

CREATE OR REPLACE PROCEDURE PROJECT_CAIDAT_CS2 AS
    STRSQL VARCHAR2(2000);
BEGIN
    STRSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE';
    EXECUTE IMMEDIATE STRSQL;
    STRSQL := 'GRANT C##P_NVCOBAN TO C##P_GIANGVIEN WITH ADMIN OPTION';
    EXECUTE IMMEDIATE STRSQL;
    STRSQL := 'GRANT SELECT ON PROJECT_GIANGVIEN_XEMPHANCONGCANHAN TO C##P_GIANGVIEN';
    EXECUTE IMMEDIATE STRSQL;
    STRSQL := 'GRANT SELECT ON PROJECT_GIANGVIEN_XEMDANGKYDCPHANCONG TO C##P_GIANGVIEN';
    EXECUTE IMMEDIATE STRSQL;
    STRSQL := 'GRANT SELECT, UPDATE(DIEMTHI, DIEMQT, DIEMCK, DIEMTK) ON PROJECT_GIANGVIEN_CAPNHATDIEMSO TO C##P_GIANGVIEN';
    EXECUTE IMMEDIATE STRSQL;

    STRSQL := 'GRANT CONNECT, CREATE SESSION TO C##P_GIANGVIEN';
    EXECUTE IMMEDIATE STRSQL;
    
END;
/