----=============================================================================
----XEM ROLE ĐÃ TẠO
--SELECT * FROM DBA_ROLES WHERE ROLE LIKE 'C##P_%';
----XEM QUYỀN TRÊN TABLE CỦA ROLE
--SELECT * FROM ROLE_TAB_PRIVS WHERE ROLE LIKE 'C##P%';
----XEM DANH SÁCH MEMBER CỦA ROLE
--SELECT * FROM DBA_ROLE_PRIVS WHERE GRANTED_ROLE LIKE 'C##P_%' AND GRANTEE = 'PROJECT_U_9'; 
--
--select table_name from all_tables where table_name like 'PROJECT_%';
--SELECT *
--FROM ALL_VIEWS
--WHERE VIEW_NAME LIKE 'PROJECT_%'
--
--SELECT * FROM USER_SYS_PRIVS; 
--SELECT * FROM USER_TAB_PRIVS WHERE GRANTEE LIKE 'PROJECT_U_%';
--SELECT * FROM USER_ROLE_PRIVS;
--
--
--select * from all_tables where table_name like 'PROJECT_%'
--
--SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'PROJECT_S_TEST_DANGKY'
--select*from project_phancong where magv = '11'
--=============================================================
--TRIGGER BEFORE DELETE
CREATE OR REPLACE TRIGGER NHANSU_BEFORE_DELETE
BEFORE DELETE
   ON PROJECT_NHANSU 
   FOR EACH ROW
   
BEGIN
    UPDATE PROJECT_DONVI
    SET TRGDV = NULL
    WHERE TRGDV = :OLD.MANV;
    DELETE FROM PROJECT_PHANCONG
    WHERE MAGV = :OLD.MANV;
END;
/

CREATE OR REPLACE TRIGGER SINHVIEN_BEFORE_DELETE
BEFORE DELETE
   ON PROJECT_SINHVIEN 
   FOR EACH ROW
   
BEGIN
    DELETE FROM PROJECT_DANGKY WHERE MASV = :OLD.MASV;
EXCEPTION
    WHEN OTHERS THEN
         dbms_output.put_line(SUBSTR(SQLERRM, 1, 64));
END;
/
CREATE OR REPLACE TRIGGER DONVI_BEFORE_DELETE
BEFORE DELETE
   ON PROJECT_DONVI
   FOR EACH ROW
   
BEGIN
    UPDATE PROJECT_NHANSU
    SET MADV = NULL
    WHERE MADV = :OLD.MADV;
    
    DELETE FROM PROJECT_HOCPHAN
    WHERE MADV = :OLD.MADV;

END;
/
CREATE OR REPLACE TRIGGER HOCPHAN_BEFORE_DELETE
BEFORE DELETE
   ON PROJECT_HOCPHAN
   FOR EACH ROW
   
BEGIN
    DELETE FROM PROJECT_KHMO
    WHERE MAHP = :OLD.MAHP;

END;
/
CREATE OR REPLACE TRIGGER KHMO_BEFORE_DELETE
BEFORE DELETE
   ON PROJECT_KHMO
   FOR EACH ROW
   
BEGIN
    DELETE FROM PROJECT_PHANCONG
    WHERE MAHP = :OLD.MAHP AND HK = :OLD.HK AND NAM = :OLD.NAM AND MACT = :OLD.MACT;

END;
/
CREATE OR REPLACE TRIGGER PHANCONG_BEFORE_DELETE
BEFORE DELETE
   ON PROJECT_PHANCONG 
   FOR EACH ROW
   
BEGIN
    DELETE FROM PROJECT_DANGKY
    WHERE MAGV = :OLD.MAGV AND MAHP = :OLD.MAHP AND HK = :OLD.HK AND NAM = :OLD.NAM AND MACT = :OLD.MACT;

END;
/



--================================================================
--CS1

CREATE OR REPLACE VIEW PROJECT_NVCOBAN_XEMTHONGTINCANHAN
AS SELECT *
FROM PROJECT_NHANSU
WHERE USERNAME = SYS_CONTEXT('USERENV', 'SESSION_USER');


CREATE OR REPLACE PROCEDURE PROJECT_CAIDAT_CS1 AS
    STRSQL VARCHAR2(2000);
BEGIN
--    STRSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE';
--    EXECUTE IMMEDIATE STRSQL;

    STRSQL := 'GRANT SELECT ON PROJECT_NVCOBAN_XEMTHONGTINCANHAN TO P_NVCOBAN';
    EXECUTE IMMEDIATE STRSQL;
    STRSQL := 'GRANT UPDATE(DT) ON PROJECT_NVCOBAN_XEMTHONGTINCANHAN TO P_NVCOBAN';
    EXECUTE IMMEDIATE STRSQL;
    
    STRSQL := 'GRANT SELECT ON PROJECT_SINHVIEN TO P_NVCOBAN';
    EXECUTE IMMEDIATE STRSQL;
    STRSQL := 'GRANT SELECT ON PROJECT_DONVI TO P_NVCOBAN';
    EXECUTE IMMEDIATE STRSQL;
    STRSQL := 'GRANT SELECT ON PROJECT_HOCPHAN TO P_NVCOBAN';
    EXECUTE IMMEDIATE STRSQL;
    STRSQL := 'GRANT SELECT ON PROJECT_KHMO TO P_NVCOBAN';
    EXECUTE IMMEDIATE STRSQL;
    
--    STRSQL := 'GRANT CONNECT TO P_NVCOBAN';
--    EXECUTE IMMEDIATE STRSQL;   
END;
/
EXEC PROJECT_CAIDAT_CS1;
/
--CS2
CREATE OR REPLACE VIEW PROJECT_GIANGVIEN_XEMPHANCONGCANHAN
AS SELECT PC.MAGV, PC.MAHP, PC.HK, PC.NAM, PC.MACT
FROM PROJECT_NHANSU NS JOIN PROJECT_PHANCONG PC ON NS.MANV = PC.MAGV
WHERE USERNAME = SYS_CONTEXT('USERENV', 'SESSION_USER');

CREATE OR REPLACE VIEW PROJECT_GIANGVIEN_XEMDANGKYDCPC
AS SELECT DK.*
FROM PROJECT_NHANSU NS JOIN PROJECT_DANGKY DK ON DK.MAGV = NS.MANV
WHERE USERNAME = SYS_CONTEXT('USERENV', 'SESSION_USER'); 


CREATE OR REPLACE PROCEDURE PROJECT_GIANGVIEN_UPDATEDIEM (
    MASV1 VARCHAR,
    MAGV1 VARCHAR,
    MAHP1 VARCHAR,
    HK1 INT, 
    NAM1 INT,
    MACT1 VARCHAR,
    
    DTH FLOAT,
    DQT FLOAT,
    DCK FLOAT
    )
AS
    ROWS_UPDATED NUMBER;
BEGIN
    UPDATE ADMIN_OLS.PROJECT_GIANGVIEN_XEMDANGKYDCPC 
    SET DIEMTH = DTH, 
        DIEMQT = DQT, 
        DIEMCK = DCK, 
        DIEMTK = 0.6*DTH + 0.1*DQT + 0.3*DCK
    WHERE MASV = MASV1 AND MAGV = MAGV1 AND MAHP = MAHP1 AND HK = HK1 AND MACT = MACT1;
    
    ROWS_UPDATED := SQL%ROWCOUNT;
    
    IF ROWS_UPDATED = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'No rows updated');
    END IF;
    
END;
/

--CREATE OR REPLACE VIEW PROJECT_GIANGVIEN_CAPNHATDIEM_DANGKY
--AS SELECT DK.MASV,DK.DIEMTHI, DK.DIEMQT, DK.DIEMCK, DK.DIEMTK
--FROM PROJECT_NHANSU NS JOIN PROJECT_DANGKY DK ON DK.MAGV = NS.MANV
--WHERE USERNAME = SYS_CONTEXT('USERENV', 'SESSION_USER'); 

CREATE OR REPLACE PROCEDURE PROJECT_CAIDAT_CS2 AS
    STRSQL VARCHAR2(2000);
BEGIN
--    STRSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE';
--    EXECUTE IMMEDIATE STRSQL;
    STRSQL := 'GRANT P_NVCOBAN TO P_GIANGVIEN WITH ADMIN OPTION';
    EXECUTE IMMEDIATE STRSQL;
    STRSQL := 'GRANT SELECT ON PROJECT_GIANGVIEN_XEMPHANCONGCANHAN TO P_GIANGVIEN';
    EXECUTE IMMEDIATE STRSQL;
    STRSQL := 'GRANT SELECT, UPDATE(DIEMTH, DIEMQT, DIEMCK, DIEMTK) ON PROJECT_GIANGVIEN_XEMDANGKYDCPC TO P_GIANGVIEN';
    EXECUTE IMMEDIATE STRSQL;
    STRSQL := 'GRANT EXECUTE ON PROJECT_GIANGVIEN_UPDATEDIEM TO P_GIANGVIEN';
    EXECUTE IMMEDIATE STRSQL;

    --STRSQL := 'GRANT CONNECT TO C##P_GIANGVIEN';
    --EXECUTE IMMEDIATE STRSQL;
    
END;
/
EXEC PROJECT_CAIDAT_CS2;
/
--CS3

CREATE OR REPLACE VIEW GIAOVU_PHANCONG AS
SELECT * FROM PROJECT_PHANCONG
WHERE MAHP IN (SELECT MAHP FROM PROJECT_HOCPHAN WHERE MADV = (SELECT MADV FROM PROJECT_DONVI WHERE MADV = 'VPK'));


CREATE OR REPLACE VIEW GIAOVU_DANGKY AS
SELECT * FROM PROJECT_DANGKY 
WHERE (( EXTRACT(MONTH FROM CURRENT_DATE) = 1 AND HK = 1) OR (EXTRACT(MONTH FROM CURRENT_DATE) = 6 AND HK = 2) OR ( EXTRACT(MONTH FROM CURRENT_DATE) = 9) AND HK = 3)
AND EXTRACT(DAY FROM CURRENT_DATE) < 30 AND EXTRACT(YEAR FROM CURRENT_DATE) = NAM ;


CREATE OR REPLACE PROCEDURE GRANT_ROLE_GIAOVU AS
BEGIN
    -- Grant C##P_NVCOBAN role to C##P_GIAOVU
    EXECUTE IMMEDIATE 'GRANT P_NVCOBAN TO P_GIAOVU';

    -- Grant select, insert, update on SINHVIEN, DONVI, HOCPHAN, KHMO to C##P_GIAOVU
    EXECUTE IMMEDIATE 'GRANT  INSERT, UPDATE ON PROJECT_SINHVIEN TO P_GIAOVU';
    EXECUTE IMMEDIATE 'GRANT  INSERT, UPDATE ON PROJECT_DONVI TO P_GIAOVU';
    EXECUTE IMMEDIATE 'GRANT  INSERT, UPDATE ON PROJECT_HOCPHAN TO P_GIAOVU';
    EXECUTE IMMEDIATE 'GRANT  INSERT, UPDATE ON PROJECT_KHMO TO P_GIAOVU';

    -- Grant select on PHANCONG to C##P_GIAOVU
    EXECUTE IMMEDIATE 'GRANT SELECT ON PROJECT_PHANCONG TO P_GIAOVU';
    EXECUTE IMMEDIATE 'GRANT SELECT,UPDATE ON GIAOVU_PHANCONG TO P_GIAOVU';

    -- Grant delete, insert on DANGKY to C##P_GIAOVU
    EXECUTE IMMEDIATE 'GRANT SELECT, DELETE, INSERT ON PROJECT_DANGKY TO P_GIAOVU';
END;
/
EXEC GRANT_ROLE_GIAOVU;
/
--CS4

CREATE OR REPLACE VIEW PROJECT_V1_TRUONGDONVI_PHANCONG
AS 
    SELECT* FROM PROJECT_PHANCONG PC
    WHERE EXISTS (SELECT HP.MAHP 
    FROM PROJECT_HOCPHAN HP JOIN PROJECT_DONVI DV ON HP.MADV = DV.MADV
    JOIN PROJECT_NHANSU NS2 ON DV.TRGDV = NS2.MANV
    WHERE HP.MAHP = PC.MAHP AND NS2.USERNAME = SYS_CONTEXT('USERENV','SESSION_USER'))
    WITH CHECK OPTION;
/
CREATE OR REPLACE VIEW PROJECT_V2_TRUONGDONVI_PHANCONG
AS
    SELECT* FROM PROJECT_PHANCONG PC
    WHERE EXISTS(SELECT NS.MANV FROM PROJECT_NHANSU NS
    JOIN PROJECT_DONVI DV ON NS.MADV = DV.MADV 
    JOIN PROJECT_NHANSU NS2 ON DV.TRGDV = NS2.MANV
    WHERE NS.MANV = PC.MAGV AND NS2.USERNAME = SYS_CONTEXT('USERENV','SESSION_USER'));
/

CREATE OR REPLACE PROCEDURE PROJECT_CS#4
AS
    BEGIN
        EXECUTE IMMEDIATE 'GRANT P_GIANGVIEN TO P_TRUONGDONVI';
        EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, DELETE, UPDATE ON PROJECT_V1_TRUONGDONVI_PHANCONG TO P_TRUONGDONVI';
        EXECUTE IMMEDIATE 'GRANT SELECT ON PROJECT_V2_TRUONGDONVI_PHANCONG TO P_TRUONGDONVI';
    END;
/
EXEC PROJECT_CS#4;
/
--CS5

CREATE OR REPLACE VIEW PROJECT_V1_TRUONGKHOA_PHANCONG
AS
    SELECT* FROM PROJECT_PHANCONG PC
    WHERE EXISTS (SELECT HP.MAHP 
    FROM PROJECT_HOCPHAN HP JOIN PROJECT_DONVI DV ON HP.MADV = DV.MADV
    WHERE HP.MAHP = PC.MAHP AND DV.TENDV = N'Văn phòng khoa');
    
CREATE OR REPLACE PROCEDURE PROJECT_CS#5
AS
    BEGIN
        EXECUTE IMMEDIATE 'GRANT P_GIANGVIEN TO P_TRUONGKHOA';
        EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE ON PROJECT_V1_TRUONGKHOA_PHANCONG TO P_TRUONGKHOA';
        EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,DELETE,UPDATE ON PROJECT_NHANSU TO P_TRUONGKHOA';
        EXECUTE IMMEDIATE 'GRANT SELECT ON PROJECT_DANGKY TO P_TRUONGKHOA';
        EXECUTE IMMEDIATE 'GRANT SELECT ON PROJECT_DONVI TO P_TRUONGKHOA';
        EXECUTE IMMEDIATE 'GRANT SELECT ON PROJECT_HOCPHAN TO P_TRUONGKHOA';
        EXECUTE IMMEDIATE 'GRANT SELECT ON PROJECT_KHMO TO P_TRUONGKHOA';
        EXECUTE IMMEDIATE 'GRANT SELECT ON PROJECT_PHANCONG TO P_TRUONGKHOA';
        EXECUTE IMMEDIATE 'GRANT SELECT ON PROJECT_SINHVIEN TO P_TRUONGKHOA';
    END;
/
EXEC PROJECT_CS#5;
--CS6
--SELECT* FROM PROJECT_PHANCONG WHERE MAGV = 23 AND MAHP = 'HTTTDN' AND HK = 3 AND NAM = 2024 AND MACT = 'CQ'
--
--=============================XÓA POLICY===========================================
BEGIN
  DBMS_RLS.DROP_POLICY(
    object_schema   => 'ADMIN_OLS',
    object_name     => 'project_sinhvien',
    policy_name     => 'SV_SELECT_SINHVIEN');
END;
/

BEGIN
  DBMS_RLS.DROP_POLICY(
     OBJECT_SCHEMA =>'ADMIN_OLS',
    OBJECT_NAME=>'PROJECT_KHMO', -- Corrected table name to uppercase
    POLICY_NAME =>'SV_SELECT_KHMO');
END;
/

BEGIN
  DBMS_RLS.DROP_POLICY(
    OBJECT_SCHEMA =>'ADMIN_OLS',
    OBJECT_NAME=>'project_HOCPHAN',
    POLICY_NAME =>'SV_SELECT_HOCPHAN');
END;
/

BEGIN
  DBMS_RLS.DROP_POLICY(
        OBJECT_SCHEMA =>'ADMIN_OLS',
        OBJECT_NAME=>'PROJECT_DANGKY',
        POLICY_NAME =>'SV_DANGKY_INSERT');
END;
/
BEGIN
  DBMS_RLS.DROP_POLICY(    
        OBJECT_SCHEMA    => 'ADMIN_OLS',
        OBJECT_NAME      => 'PROJECT_DANGKY',
        POLICY_NAME      => 'SV_DANGKY_DELETE');
END;
/

BEGIN
  DBMS_RLS.DROP_POLICY(    
        OBJECT_SCHEMA    => 'ADMIN_OLS',
        OBJECT_NAME      => 'PROJECT_DANGKY',
        POLICY_NAME      => 'SV_UPDATE_DIEM');
END;
/

BEGIN
  DBMS_RLS.DROP_POLICY(    
        OBJECT_SCHEMA =>'ADMIN_OLS',
        OBJECT_NAME=>'PROJECT_DANGKY',
        POLICY_NAME =>'SV_DANGKY_SELECT');
END;
/
--=======================================================

CREATE OR REPLACE FUNCTION SV_SELECT_FUNCTION (
    P_SCHEMA VARCHAR2,
    P_OBJ VARCHAR2
)
RETURN VARCHAR2
AS
    L_USER VARCHAR2(100); -- Changed USER to L_USER to avoid conflicts
    MASV VARCHAR2(100); -- Corrected the declaration
BEGIN
    L_USER := SYS_CONTEXT('USERENV','SESSION_USER'); -- Corrected the typo in USERENV
    
    --KIỂM TRA USER CONNECT CÓ PHẢI LÀ SV KHÔNG, NẾU KHÔNG THÌ KHÔNG ÁP DỤNG CHÍNH SÁCH 
    IF (SYS_CONTEXT('USERENV','SESSION_USER') NOT LIKE '%SV%') THEN
        RETURN NULL;
    END IF;
    
    MASV := REPLACE(L_USER, 'SV', ''); -- Corrected the typo in variable name
    RETURN 'MASV = ''' || MASV || '''';
END;
/
BEGIN
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA =>'ADMIN_OLS',
        OBJECT_NAME=>'project_sinhvien',
        POLICY_NAME =>'SV_SELECT_SINHVIEN',
        POLICY_FUNCTION=>'SV_SELECT_FUNCTION',
        STATEMENT_TYPES=>'SELECT, UPDATE',
        UPDATE_CHECK => TRUE
);
END;
/
grant SELECT ON PROJECT_SINHVIEN TO P_SINHVIEN;
grant UPDATE (DCHI,DT) ON PROJECT_SINHVIEN TO P_SINHVIEN;
-- Xem danh sách tất cả học phần (HOCPHAN), kế hoạch mở môn (KHMO) của chương
-- trình đào tạo mà sinh viên đang theo học.
CREATE OR REPLACE FUNCTION SV_SELECT_KHMO_FUNCTION
  (P_SCHEMA VARCHAR2, P_OBJ VARCHAR2)
RETURN VARCHAR2
AS
  MA VARCHAR(5);
  STRSQL VARCHAR2(2000);
  CURSOR CUR IS (
    SELECT MACT
    FROM PROJECT_SINHVIEN
    WHERE MASV = REPLACE(SYS_CONTEXT('USERENV','SESSION_USER'), 'SV', ''));
BEGIN
  STRSQL := ''; 
  OPEN CUR;
  LOOP
    FETCH CUR INTO MA;
    EXIT WHEN CUR%NOTFOUND;
    IF (STRSQL IS NOT NULL) THEN
      STRSQL := STRSQL || ',''' || MA || ''''; -- Corrected concatenation operator
    ELSE
      STRSQL := '''' || MA || ''''; -- Corrected concatenation operator
    END IF;
  END LOOP;
  
  --KIỂM TRA USER CONNECT CÓ PHẢI LÀ SV KHÔNG, NẾU KHÔNG THÌ KHÔNG ÁP DỤNG CHÍNH SÁCH 
    IF (SYS_CONTEXT('USERENV','SESSION_USER') NOT LIKE '%SV%') THEN
        RETURN NULL;
    END IF;
    
  RETURN 'MACT IN (' || STRSQL || ')';
END;
/
BEGIN
  DBMS_RLS.ADD_POLICY(
    OBJECT_SCHEMA =>'ADMIN_OLS',
    OBJECT_NAME=>'PROJECT_KHMO', -- Corrected table name to uppercase
    POLICY_NAME =>'SV_SELECT_KHMO',
    POLICY_FUNCTION=>'SV_SELECT_KHMO_FUNCTION',
    STATEMENT_TYPES=>'SELECT',
    UPDATE_CHECK => TRUE
  );
END;
/

CREATE OR REPLACE FUNCTION SV_SELECT_HOCPHAN_FUNCTION
 (P_SCHEMA VARCHAR2, P_OBJ VARCHAR2)
RETURN VARCHAR2
AS
 MA VARCHAR2(1000);
 STRSQL VARCHAR2(2000);
 CURSOR CUR IS (SELECT KHM1.MAHP FROM ADMIN_OLS.PROJECT_KHMO KHM1 WHERE KHM1.MACT = 
 (SELECT SV.MACT FROM ADMIN_OLS.PROJECT_SINHVIEN SV WHERE SV.MASV = SUBSTR(SYS_CONTEXT('USERENV','SESSION_USER'),3)  )
);
BEGIN
  -- Check if the user is not a student, if not then do not apply the policy
    IF (SYS_CONTEXT('USERENV','SESSION_USER') NOT LIKE '%SV%') THEN
        RETURN NULL;
    END IF;
    
 OPEN CUR;
 LOOP
 FETCH CUR INTO MA;
 EXIT WHEN CUR%NOTFOUND;
 IF (STRSQL IS NOT NULL) THEN
 STRSQL := STRSQL || ''',''';
 END IF;
 STRSQL := STRSQL || MA ;  
 END LOOP;
 CLOSE CUR;

 RETURN 'MAHP IN (''' || STRSQL || ''')';
END; 
/
BEGIN
  DBMS_RLS.ADD_POLICY(
    OBJECT_SCHEMA =>'ADMIN_OLS',
    OBJECT_NAME=>'project_HOCPHAN',
    POLICY_NAME =>'SV_SELECT_HOCPHAN',
    POLICY_FUNCTION=>'SV_SELECT_HOCPHAN_FUNCTION',
    STATEMENT_TYPES=>'SELECT'
  );
END;
/
-- Thêm, Xóa các dòng dữ liệu đăng ký học phần (ĐANGKY) liên quan đến chính sinh
--viên đó trong học kỳ của năm học hiện tại (nếu thời điểm hiệu chỉnh đăng ký còn hợp
--lệ).
CREATE OR REPLACE FUNCTION SV_INSERT_DELETE_DANGKY_FUNCTION (
    P_SCHEMA VARCHAR2,
    P_OBJ VARCHAR2
)
RETURN VARCHAR2
AS
    v_limit_date DATE;
    v_masv VARCHAR2(50);
    v_hk int;
    v_year int;
    v_month VARCHAR2(50);
BEGIN   
--KIỂM TRA USER CONNECT CÓ PHẢI LÀ SV KHÔNG, NẾU KHÔNG THÌ KHÔNG ÁP DỤNG CHÍNH SÁCH 
    IF (SYS_CONTEXT('USERENV','SESSION_USER') NOT LIKE '%SV%') THEN
        RETURN NULL;
    END IF;
    
    -- Set the end of the valid registration period   
    SELECT EXTRACT(YEAR FROM SYSDATE) into v_year FROM DUAL;
    SELECT MAX(HK) into v_hk FROM ADMIN_OLS.PROJECT_KHMO WHERE NAM = v_year ;
    
    IF  EXTRACT(MONTH FROM CURRENT_DATE) >= 9 THEN 
        v_hk := 3;
    ELSIF EXTRACT(MONTH FROM CURRENT_DATE) >= 5 THEN  
        v_hk := 2;
    ELSIF EXTRACT(MONTH FROM CURRENT_DATE) >= 1 THEN  
        v_hk := 1;
    END IF;
    

    IF v_hk = 1 THEN
        v_month := '01';
    ELSIF v_hk = 2 THEN
        v_month := '05';
    ELSIF v_hk = 3 THEN
        v_month := '09';
    END IF;
    v_limit_date := TO_DATE(v_year || '/' || v_month || '/14', 'yyyy/mm/dd');
    
    -- Get the student ID from the current session user
    v_masv := REPLACE(SYS_CONTEXT('USERENV', 'SESSION_USER'), 'SV', '');
    
    
    -- Check if the current date is within the valid registration period
    IF CURRENT_DATE <= v_limit_date THEN
        -- Allow operations for the current student in the current academic year and semester
        RETURN 'MASV = ''' || v_masv || '''';
    ELSE
        -- Disallow operations
        RETURN '1=0';
    END IF;
END;
/
BEGIN
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA =>'ADMIN_OLS',
        OBJECT_NAME=>'PROJECT_DANGKY',
        POLICY_NAME =>'SV_DANGKY_INSERT',
        POLICY_FUNCTION=>'SV_INSERT_DELETE_DANGKY_FUNCTION',
        STATEMENT_TYPES=> 'INSERT',
        UPDATE_CHECK => TRUE

        
    );
END;
/
BEGIN
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA    => 'ADMIN_OLS',
        OBJECT_NAME      => 'PROJECT_DANGKY',
        POLICY_NAME      => 'SV_DANGKY_DELETE',
        FUNCTION_SCHEMA  => 'ADMIN_OLS', -- Schema where the function is located
        POLICY_FUNCTION  => 'SV_INSERT_DELETE_DANGKY_FUNCTION',
        STATEMENT_TYPES  => 'DELETE'
    );
END;
/
-- Sinh viên không được chỉnh sửa trên các trường liên quan đến điểm.
CREATE OR REPLACE FUNCTION SV_UPDATE_DIEM_FUNCTION (
    P_SCHEMA VARCHAR2,
    P_OBJ VARCHAR2
)
RETURN VARCHAR2
AS
BEGIN
    --KIỂM TRA USER CONNECT CÓ PHẢI LÀ SV KHÔNG, NẾU KHÔNG THÌ KHÔNG ÁP DỤNG CHÍNH SÁCH 
    IF (SYS_CONTEXT('USERENV','SESSION_USER') NOT LIKE '%SV%') THEN
        RETURN NULL;
    END IF;

    -- This policy will always be FALSE for UPDATE operations on grade-related fields
    RETURN '1=0'; -- Prevent all updates
END;
/
BEGIN
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA    => 'ADMIN_OLS',
        OBJECT_NAME      => 'PROJECT_DANGKY',
        POLICY_NAME      => 'SV_UPDATE_DIEM',
        FUNCTION_SCHEMA  => 'ADMIN_OLS', -- Schema where the function is located
        POLICY_FUNCTION  => 'SV_UPDATE_DIEM_FUNCTION',
        STATEMENT_TYPES  => 'UPDATE',
        sec_relevant_cols    => 'DIEMTH, DIEMQT, DIEMCK, DIEMTK' -- Columns to restrict
    );
END;
/
-- Sinh viên được Xem tất cả thông tin trên quan hệ ĐANGKY tại các dòng dữ liệu liên
-- quan đến chính sinh 
BEGIN
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA =>'ADMIN_OLS',
        OBJECT_NAME=>'PROJECT_DANGKY',
        POLICY_NAME =>'SV_DANGKY_SELECT',
        POLICY_FUNCTION=>'SV_SELECT_FUNCTION',
        STATEMENT_TYPES=>'SELECT'
    );
END;
/
GRANT SELECT ON PROJECT_SINHVIEN TO P_SINHVIEN;
GRANT UPDATE (DCHI,DT) ON PROJECT_SINHVIEN TO P_SINHVIEN;
GRANT SELECT ON PROJECT_HOCPHAN TO P_SINHVIEN;
GRANT SELECT ON PROJECT_KHMO TO P_SINHVIEN;
GRANT SELECT ON PROJECT_PHANCONG TO P_SINHVIEN;
GRANT INSERT ON PROJECT_DANGKY TO P_SINHVIEN;
GRANT DELETE ON PROJECT_DANGKY TO P_SINHVIEN;
GRANT SELECT ON PROJECT_DANGKY TO P_SINHVIEN;

