--kết nối sang user vừa tạo với chế default-----------------------------------------------
alter session set "_oracle_script" = true;

CREATE TABLE PROJECT_NHANSU
(
    MANV VARCHAR(3),
    HOTEN NVARCHAR2(50),
    PHAI NVARCHAR2(10),
    NGSINH DATE,
    PHUCAP INT,
    DT VARCHAR(10),
    VAITRO VARCHAR2(50),
    MADV VARCHAR(5),
    
    PRIMARY KEY(MANV)
);

CREATE TABLE PROJECT_SINHVIEN
(
    MASV VARCHAR(3),
    HOTEN NVARCHAR2(50),
    PHAI NVARCHAR2(10),
    NGSINH DATE,
    DCHI VARCHAR2(100),
    DT VARCHAR(10),
    MACT VARCHAR(5),
    MANGANH VARCHAR(5),
    SOTCTL INT,
    DTBTL FLOAT,
    
    PRIMARY KEY(MASV)
);
CREATE TABLE PROJECT_DONVI
(
    MADV VARCHAR(5),
    TENDV VARCHAR2(50),
    TRGDV VARCHAR(3),
    PRIMARY KEY(MADV)
);

CREATE TABLE PROJECT_HOCPHAN
(
    MAHP VARCHAR(10),
    TENHP VARCHAR2(50),
    SOTC INT,
    SSLT INT,
    STTH INT, 
    SOSVTD INT,
    MADV VARCHAR(5),
    
    PRIMARY KEY(MAHP)
);

CREATE TABLE PROJECT_KHMO
(
    MAHP VARCHAR(10),
    HK INT,
    NAM INT,
    MACT VARCHAR(5),
    PRIMARY KEY(MAHP, HK,NAM,MACT)
);

CREATE TABLE PROJECT_PHANCONG
(
    MAGV VARCHAR(3),
    MAHP VARCHAR(10),
    HK INT,
    NAM INT,
    MACT VARCHAR(5),
    
    PRIMARY KEY(MAGV,MAHP,HK,NAM,MACT)
);
CREATE TABLE PROJECT_DANGKY
(
    MASV VARCHAR(3),
    MAGV VARCHAR(3),
    MAHP VARCHAR(10),
    HK INT, 
    NAM INT,
    MACT VARCHAR(5),
    DIEMTHI FLOAT,
    DIEMQT FLOAT,
    DIEMCK FLOAT,
    DIEMTK FLOAT,
    
    PRIMARY KEY(MASV,MAGV,MAHP,HK,NAM,MACT)
);

ALTER TABLE PROJECT_NHANSU
ADD
    CONSTRAINT FK_NS_DV
    FOREIGN KEY (MADV)
    REFERENCES PROJECT_DONVI;

ALTER TABLE PROJECT_DONVI
ADD
    CONSTRAINT FK_DV_NS
    FOREIGN KEY (TRGDV)
    REFERENCES PROJECT_NHANSU;
    
ALTER TABLE PROJECT_HOCPHAN
ADD
    CONSTRAINT FK_HP_DV
    FOREIGN KEY (MADV)
    REFERENCES PROJECT_DONVI;
    
ALTER TABLE PROJECT_KHMO
ADD
    CONSTRAINT FK_KHMO_HP
    FOREIGN KEY (MAHP)
    REFERENCES PROJECT_HOCPHAN;
    
ALTER TABLE PROJECT_PHANCONG
ADD
    CONSTRAINT FK_PC_NS
    FOREIGN KEY (MAGV)
    REFERENCES PROJECT_NHANSU;

ALTER TABLE PROJECT_PHANCONG
ADD
    CONSTRAINT FK_PC_KHMO
    FOREIGN KEY (MAHP,HK,NAM,MACT)
    REFERENCES PROJECT_KHMO;  

ALTER TABLE PROJECT_DANGKY
ADD
    CONSTRAINT FK_DK_SV
    FOREIGN KEY (MASV)
    REFERENCES PROJECT_SINHVIEN;

ALTER TABLE PROJECT_DANGKY
ADD
    CONSTRAINT FK_DK_PC
    FOREIGN KEY (MAGV,MAHP,HK,NAM,MACT)
    REFERENCES PROJECT_PHANCONG;

CREATE ROLE C##P_NVCOBAN;
CREATE ROLE C##P_GIANGVIEN;
CREATE ROLE C##P_GIAOVU;
CREATE ROLE C##P_TRUONGDONVI;
CREATE ROLE C##P_TRUONGKHOA;
CREATE ROLE C##P_SINHVIEN;

--XEM ROLE ĐÃ TẠO
SELECT * FROM DBA_ROLES WHERE ROLE LIKE 'C##P_%';
--XEM QUYỀN TRÊN TABLE CỦA ROLE
SELECT * FROM ROLE_TAB_PRIVS WHERE ROLE LIKE 'C##P_%';
--XEM DANH SÁCH MEMBER CỦA ROLE
SELECT * FROM DBA_ROLE_PRIVS WHERE GRANTED_ROLE LIKE 'C##P_%'; 

-- Trên quan hệ SINHVIEN, sinh viên chỉ được xem thông tin của chính mình

-- Chỉnh sửa thông tin địa chỉ (ĐCHI) và số điện thoại liên lạc (ĐT) của chính sinh viên.
--- Xem danh sách tất cả học phần (HOCPHAN), kế hoạch mở môn (KHMO) của chương trình đào tạo mà sinh viên đang theo học.
--- Thêm, Xóa các dòng dữ liệu đăng ký học phần (ĐANGKY) liên quan đến chính sinh viên đó trong học kỳ của năm học hiện tại (nếu thời điểm hiệu chỉnh đăng ký còn hợp lệ).
--- Sinh viên không được chỉnh sửa trên các trường liên quan đến điểm.
--- Sinh viên được Xem tất cả thông tin trên quan hệ ĐANGKY tại các dòng dữ liệu liên quan đến chính sinh viên
SELECT * FROM project_sinhvien
/

CREATE OR REPLACE FUNCTION PC1_FUNCTION (
    P_SCHEMA VARCHAR2,
    P_OBJ VARCHAR2
)
RETURN VARCHAR2
AS
    USER VARCHAR2(100); -- Corrected the data type declaration
BEGIN
    USER := SYS_CONTEXT('USERENV','SESSION_USER'); -- Corrected the typo in USERENV
    RETURN 'MASV = ''' || USER || '''';
END;
/
BEGIN
 DBMS_RLS.ADD_POLICY(
 OBJECT_SCHEMA =>'C##ADMIN',
 OBJECT_NAME=>'project_sinhvien',
 POLICY_NAME =>'PC1',
 POLICY_FUNCTION=>'PC1_FUNCTION',
 STATEMENT_TYPES=>'SELECT');
END; 
/
